//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACS.DataAccessLayer.Entitites
{
    using System;
    
    public enum AuditType : int
    {
        Create = 0,
        Update = 1,
        Delete = 2,
        Start = 3,
        Stop = 4,
        Performance = 5
    }
}
