//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACS.DataAccessLayer.Entitites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class SACSEntitiesContainer : DbContext
    {
        public SACSEntitiesContainer()
            : base("name=SACSEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ServiceApplication> ServiceApplications { get; set; }
        public virtual DbSet<ServiceApplicationAudit> ServiceApplicationAudits { get; set; }
        public virtual DbSet<SystemAudit> SystemAudits { get; set; }
        public virtual DbSet<ServiceApplicationPerfomance> ServiceApplicationPerfomances { get; set; }
        public virtual DbSet<ServiceApplicationHistory> ServiceApplicationHistories { get; set; }
    }
}
