//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACS.DataAccessLayer.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceApplicationPerfomance
    {
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public int ServiceApplicationId { get; set; }
        public string Guid { get; set; }
        public bool Failed { get; set; }
    
        public virtual ServiceApplication ServiceApplication { get; set; }
    }
}
