//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACS.DataAccessLayer.Entitites
{
    using System;
    
    public enum StartupType : int
    {
        NotSet = 0,
        Manual = 1,
        Automatic = 2,
        Disabled = 3
    }
}
